//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRFAnalyzer.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XRFAnalyzer.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRFAnalyzer.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string ChannelToggleOption {
            get {
                return ResourceManager.GetString("ChannelToggleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string EnergyToggleOption {
            get {
                return ResourceManager.GetString("EnergyToggleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic scale.
        /// </summary>
        internal static string LogarithmicScaleToggleLabel {
            get {
                return ResourceManager.GetString("LogarithmicScaleToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        internal static string MainMenuOption1 {
            get {
                return ResourceManager.GetString("MainMenuOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum processing.
        /// </summary>
        internal static string MainMenuOption2 {
            get {
                return ResourceManager.GetString("MainMenuOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string MainMenuOption3 {
            get {
                return ResourceManager.GetString("MainMenuOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results.
        /// </summary>
        internal static string MainMenuOption4 {
            get {
                return ResourceManager.GetString("MainMenuOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainMenuOption5 {
            get {
                return ResourceManager.GetString("MainMenuOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables of XRF constants.
        /// </summary>
        internal static string MainMenuOption6 {
            get {
                return ResourceManager.GetString("MainMenuOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainMenuOption7 {
            get {
                return ResourceManager.GetString("MainMenuOption7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaks.
        /// </summary>
        internal static string OperationMenuOption1 {
            get {
                return ResourceManager.GetString("OperationMenuOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        internal static string OperationMenuOption2 {
            get {
                return ResourceManager.GetString("OperationMenuOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string OperationMenuOption3 {
            get {
                return ResourceManager.GetString("OperationMenuOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum peaks.
        /// </summary>
        internal static string OperationMenuOption4 {
            get {
                return ResourceManager.GetString("OperationMenuOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitative Analysis.
        /// </summary>
        internal static string OperationMenuOption5 {
            get {
                return ResourceManager.GetString("OperationMenuOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantitative Analysis.
        /// </summary>
        internal static string OperationMenuOption6 {
            get {
                return ResourceManager.GetString("OperationMenuOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables of XRF constants.
        /// </summary>
        internal static string OperationMenuOption7 {
            get {
                return ResourceManager.GetString("OperationMenuOption7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string SpectrumWpfPlotXLabel {
            get {
                return ResourceManager.GetString("SpectrumWpfPlotXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy [kEv].
        /// </summary>
        internal static string SpectrumWpfPlotXLabelAlt {
            get {
                return ResourceManager.GetString("SpectrumWpfPlotXLabelAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts.
        /// </summary>
        internal static string SpectrumWpfPlotYLabel {
            get {
                return ResourceManager.GetString("SpectrumWpfPlotYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis unit.
        /// </summary>
        internal static string XAxisUnitToggleLabel {
            get {
                return ResourceManager.GetString("XAxisUnitToggleLabel", resourceCulture);
            }
        }
    }
}
