//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRFAnalyzer.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XRFAnalyzer.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add found peaks.
        /// </summary>
        internal static string AddFoundPeaks {
            get {
                return ResourceManager.GetString("AddFoundPeaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add peak.
        /// </summary>
        internal static string AddPeak {
            get {
                return ResourceManager.GetString("AddPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzed.
        /// </summary>
        internal static string AnalyzedSpectrum {
            get {
                return ResourceManager.GetString("AnalyzedSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRFAnalyzer.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate concentrations.
        /// </summary>
        internal static string CalculateConcentrations {
            get {
                return ResourceManager.GetString("CalculateConcentrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate concentrations (mono).
        /// </summary>
        internal static string CalculateConcentrationsMono {
            get {
                return ResourceManager.GetString("CalculateConcentrationsMono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration points.
        /// </summary>
        internal static string CalibrationPoints {
            get {
                return ResourceManager.GetString("CalibrationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centroid.
        /// </summary>
        internal static string Centroid {
            get {
                return ResourceManager.GetString("Centroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm identification.
        /// </summary>
        internal static string ConfirmIdentification {
            get {
                return ResourceManager.GetString("ConfirmIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentFile.
        /// </summary>
        internal static string CurrentFile {
            get {
                return ResourceManager.GetString("CurrentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detector.
        /// </summary>
        internal static string Detector {
            get {
                return ResourceManager.GetString("Detector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string EmissionLine {
            get {
                return ResourceManager.GetString("EmissionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy [keV].
        /// </summary>
        internal static string EnergyKev {
            get {
                return ResourceManager.GetString("EnergyKev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy [keV].
        /// </summary>
        internal static string EnergyToggleOption {
            get {
                return ResourceManager.GetString("EnergyToggleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results.
        /// </summary>
        internal static string ExportResults {
            get {
                return ResourceManager.GetString("ExportResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find peaks.
        /// </summary>
        internal static string FindPeaksButtonLabel {
            get {
                return ResourceManager.GetString("FindPeaksButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string FindPeaksDistanceLabel {
            get {
                return ResourceManager.GetString("FindPeaksDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string FindPeaksHeightLabel {
            get {
                return ResourceManager.GetString("FindPeaksHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak detection algorithm parameters.
        /// </summary>
        internal static string FindPeaksParametersLabel {
            get {
                return ResourceManager.GetString("FindPeaksParametersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateau size.
        /// </summary>
        internal static string FindPeaksPlateauSizeLabel {
            get {
                return ResourceManager.GetString("FindPeaksPlateauSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prominence.
        /// </summary>
        internal static string FindPeaksProminenceLabel {
            get {
                return ResourceManager.GetString("FindPeaksProminenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelHeight.
        /// </summary>
        internal static string FindPeaksRelHeightLabel {
            get {
                return ResourceManager.GetString("FindPeaksRelHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        internal static string FindPeaksThresholdLabel {
            get {
                return ResourceManager.GetString("FindPeaksThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string FindPeaksWidthLabel {
            get {
                return ResourceManager.GetString("FindPeaksWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWHM.
        /// </summary>
        internal static string FWHM {
            get {
                return ResourceManager.GetString("FWHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left base channel.
        /// </summary>
        internal static string LeftBaseChannel {
            get {
                return ResourceManager.GetString("LeftBaseChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        internal static string LoadAnalyzedSpectrum {
            get {
                return ResourceManager.GetString("LoadAnalyzedSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic scale.
        /// </summary>
        internal static string LogarithmicScaleToggleLabel {
            get {
                return ResourceManager.GetString("LogarithmicScaleToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum processing.
        /// </summary>
        internal static string MainMenuOption2 {
            get {
                return ResourceManager.GetString("MainMenuOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string MainMenuOption3 {
            get {
                return ResourceManager.GetString("MainMenuOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables of XRF constants.
        /// </summary>
        internal static string MainMenuOption6 {
            get {
                return ResourceManager.GetString("MainMenuOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainMenuOption7 {
            get {
                return ResourceManager.GetString("MainMenuOption7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove peaks.
        /// </summary>
        internal static string OperationMenuAddOrRemovePeaksLabel {
            get {
                return ResourceManager.GetString("OperationMenuAddOrRemovePeaksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string OperationMenuBackgroundLabel {
            get {
                return ResourceManager.GetString("OperationMenuBackgroundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        internal static string OperationMenuCalibrationLabel {
            get {
                return ResourceManager.GetString("OperationMenuCalibrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ray data tables.
        /// </summary>
        internal static string OperationMenuDataTablesLabel {
            get {
                return ResourceManager.GetString("OperationMenuDataTablesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaks.
        /// </summary>
        internal static string OperationMenuPeaksLabel {
            get {
                return ResourceManager.GetString("OperationMenuPeaksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitative Analysis.
        /// </summary>
        internal static string OperationMenuQualitativeAnalysisLabel {
            get {
                return ResourceManager.GetString("OperationMenuQualitativeAnalysisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantitative Analysis.
        /// </summary>
        internal static string OperationMenuQuantitativeAnalysisLabel {
            get {
                return ResourceManager.GetString("OperationMenuQuantitativeAnalysisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum peaks.
        /// </summary>
        internal static string OperationMenuSumPeaksLabel {
            get {
                return ResourceManager.GetString("OperationMenuSumPeaksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apex channel.
        /// </summary>
        internal static string PeakApexChannelLabel {
            get {
                return ResourceManager.GetString("PeakApexChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apex energy.
        /// </summary>
        internal static string PeakApexEnergyLabel {
            get {
                return ResourceManager.GetString("PeakApexEnergyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel range.
        /// </summary>
        internal static string PeakChannelRangeLabel {
            get {
                return ResourceManager.GetString("PeakChannelRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy range.
        /// </summary>
        internal static string PeakEnergyRangeLabel {
            get {
                return ResourceManager.GetString("PeakEnergyRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross area.
        /// </summary>
        internal static string PeakGrossAreaLabel {
            get {
                return ResourceManager.GetString("PeakGrossAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Height.
        /// </summary>
        internal static string PeakHeightLabel {
            get {
                return ResourceManager.GetString("PeakHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak properties.
        /// </summary>
        internal static string PeakInfoLabel {
            get {
                return ResourceManager.GetString("PeakInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net area.
        /// </summary>
        internal static string PeakNetAreaLabel {
            get {
                return ResourceManager.GetString("PeakNetAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary radiation energy.
        /// </summary>
        internal static string PrimaryRadiationEnergy {
            get {
                return ResourceManager.GetString("PrimaryRadiationEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string PrimarySpectrum {
            get {
                return ResourceManager.GetString("PrimarySpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified line.
        /// </summary>
        internal static string QualitativeAnalysisIdentifiedLineLabel {
            get {
                return ResourceManager.GetString("QualitativeAnalysisIdentifiedLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove background.
        /// </summary>
        internal static string RemoveBackgroundLabel {
            get {
                return ResourceManager.GetString("RemoveBackgroundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected peak.
        /// </summary>
        internal static string RemoveSelectedPeak {
            get {
                return ResourceManager.GetString("RemoveSelectedPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right base channel.
        /// </summary>
        internal static string RightBaseChannel {
            get {
                return ResourceManager.GetString("RightBaseChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum type:.
        /// </summary>
        internal static string SpectrumType {
            get {
                return ResourceManager.GetString("SpectrumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string SpectrumWpfPlotXLabel {
            get {
                return ResourceManager.GetString("SpectrumWpfPlotXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy [keV].
        /// </summary>
        internal static string SpectrumWpfPlotXLabelAlt {
            get {
                return ResourceManager.GetString("SpectrumWpfPlotXLabelAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts.
        /// </summary>
        internal static string SpectrumWpfPlotYLabel {
            get {
                return ResourceManager.GetString("SpectrumWpfPlotYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sum peak detected.
        /// </summary>
        internal static string SumPeaksEmptyMessage {
            get {
                return ResourceManager.GetString("SumPeaksEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete a sum peak, select a row and press delete..
        /// </summary>
        internal static string SumPeaksHintMessage {
            get {
                return ResourceManager.GetString("SumPeaksHintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch spectrum.
        /// </summary>
        internal static string SwitchSpectrum {
            get {
                return ResourceManager.GetString("SwitchSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo background removal.
        /// </summary>
        internal static string UndoBackgroundRemovalLabel {
            get {
                return ResourceManager.GetString("UndoBackgroundRemovalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string WindowChoiceLabel {
            get {
                return ResourceManager.GetString("WindowChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis unit.
        /// </summary>
        internal static string XAxisUnitToggleLabel {
            get {
                return ResourceManager.GetString("XAxisUnitToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current primary X-ray spectrum.
        /// </summary>
        internal static string XRaySourceSpectrumFileLabel {
            get {
                return ResourceManager.GetString("XRaySourceSpectrumFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load primary X-ray spectrum.
        /// </summary>
        internal static string XRaySourceSpectrumLoad {
            get {
                return ResourceManager.GetString("XRaySourceSpectrumLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        internal static string ZhangFitIterationsLabel {
            get {
                return ResourceManager.GetString("ZhangFitIterationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothness (Lambda).
        /// </summary>
        internal static string ZhangFitSmoothnessLabel {
            get {
                return ResourceManager.GetString("ZhangFitSmoothnessLabel", resourceCulture);
            }
        }
    }
}
