# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import XRFAnalyzer_pb2 as XRFAnalyzer__pb2


class XRFAnalyzerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindPeaksMessage = channel.unary_unary(
                '/XRFAnalyzerService/FindPeaksMessage',
                request_serializer=XRFAnalyzer__pb2.FindPeaksRequest.SerializeToString,
                response_deserializer=XRFAnalyzer__pb2.FindPeaksReply.FromString,
                )
        self.BackgroundMessage = channel.unary_unary(
                '/XRFAnalyzerService/BackgroundMessage',
                request_serializer=XRFAnalyzer__pb2.BackgroundRequest.SerializeToString,
                response_deserializer=XRFAnalyzer__pb2.BackgroundReply.FromString,
                )
        self.QuantificationMessage = channel.unary_unary(
                '/XRFAnalyzerService/QuantificationMessage',
                request_serializer=XRFAnalyzer__pb2.QuantificationRequest.SerializeToString,
                response_deserializer=XRFAnalyzer__pb2.QuantificationReply.FromString,
                )


class XRFAnalyzerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindPeaksMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackgroundMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuantificationMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XRFAnalyzerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindPeaksMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPeaksMessage,
                    request_deserializer=XRFAnalyzer__pb2.FindPeaksRequest.FromString,
                    response_serializer=XRFAnalyzer__pb2.FindPeaksReply.SerializeToString,
            ),
            'BackgroundMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.BackgroundMessage,
                    request_deserializer=XRFAnalyzer__pb2.BackgroundRequest.FromString,
                    response_serializer=XRFAnalyzer__pb2.BackgroundReply.SerializeToString,
            ),
            'QuantificationMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.QuantificationMessage,
                    request_deserializer=XRFAnalyzer__pb2.QuantificationRequest.FromString,
                    response_serializer=XRFAnalyzer__pb2.QuantificationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'XRFAnalyzerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class XRFAnalyzerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindPeaksMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/XRFAnalyzerService/FindPeaksMessage',
            XRFAnalyzer__pb2.FindPeaksRequest.SerializeToString,
            XRFAnalyzer__pb2.FindPeaksReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BackgroundMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/XRFAnalyzerService/BackgroundMessage',
            XRFAnalyzer__pb2.BackgroundRequest.SerializeToString,
            XRFAnalyzer__pb2.BackgroundReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QuantificationMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/XRFAnalyzerService/QuantificationMessage',
            XRFAnalyzer__pb2.QuantificationRequest.SerializeToString,
            XRFAnalyzer__pb2.QuantificationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
