# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: XRFAnalyzer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11XRFAnalyzer.proto\"\xb2\x01\n\x10\x46indPeaksRequest\x12\x0e\n\x06\x63ounts\x18\x01 \x03(\x01\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x11\n\tthreshold\x18\x03 \x01(\x05\x12\x10\n\x08\x64istance\x18\x04 \x01(\x05\x12\x12\n\nprominence\x18\x05 \x01(\x05\x12\r\n\x05width\x18\x06 \x01(\x05\x12\x0c\n\x04wlen\x18\x07 \x01(\x05\x12\x12\n\nrel_height\x18\x08 \x01(\x01\x12\x14\n\x0cplateau_size\x18\t \x01(\x05\"H\n\x0e\x46indPeaksReply\x12\r\n\x05peaks\x18\x01 \x03(\x05\x12\x12\n\nleft_bases\x18\x02 \x03(\x05\x12\x13\n\x0bright_bases\x18\x03 \x03(\x05\"H\n\x11\x42\x61\x63kgroundRequest\x12\x0e\n\x06\x63ounts\x18\x01 \x03(\x01\x12\x0f\n\x07lambda_\x18\x02 \x01(\x05\x12\x12\n\niterations\x18\x03 \x01(\x05\"+\n\x0f\x42\x61\x63kgroundReply\x12\x18\n\x10\x63orrected_counts\x18\x01 \x03(\x01\x32\x87\x01\n\x12XRFAnalyzerService\x12\x36\n\x10\x46indPeaksMessage\x12\x11.FindPeaksRequest\x1a\x0f.FindPeaksReply\x12\x39\n\x11\x42\x61\x63kgroundMessage\x12\x12.BackgroundRequest\x1a\x10.BackgroundReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'XRFAnalyzer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FINDPEAKSREQUEST._serialized_start=22
  _FINDPEAKSREQUEST._serialized_end=200
  _FINDPEAKSREPLY._serialized_start=202
  _FINDPEAKSREPLY._serialized_end=274
  _BACKGROUNDREQUEST._serialized_start=276
  _BACKGROUNDREQUEST._serialized_end=348
  _BACKGROUNDREPLY._serialized_start=350
  _BACKGROUNDREPLY._serialized_end=393
  _XRFANALYZERSERVICE._serialized_start=396
  _XRFANALYZERSERVICE._serialized_end=531
# @@protoc_insertion_point(module_scope)
